### ISSUE TITLE
Allow Pygment options

### ISSUE THREAD

**Issue by sanbornm** [fnando/kitabu#27]
I have a bunch of PHP code that I would like to have syntax highlighting; however, I normally don't show the entire file leaving off the start tag '<?php' causing highlighter to skip highlighting.

pygments.rb has an option for this which can be set using the option 'startinline':

In Kitabu's highlight.rb file this line:

```Pygments.highlight(code, :lexer => language, :options => {:encoding => "utf-8", :startinline => true})```

Fixes this for my particular case but it would be nice to be able to set options for example:

```
@@@ php startinline
public function indexAction() {
    echo 'Hello World!';
}
@@@
```

or something similar.  Any ideas on how we could handle this since kitabu supports different syntax highlighters?

**Comment by fnando** [comment]
Implemented by 915877a5264d74ad9915ab3f7734daf7ef0e5802
