### ISSUE TITLE
Questions about templates

### ISSUE THREAD

**Issue by DanielKehoe** [fnando/kitabu#35]
The generator creates two template directories:
```
├── templates
│   ├── epub
│   │   ├── cover.erb
│   │   ├── cover.png
│   │   ├── page.erb
│   │   └── user.css
│   └── html
│       ├── layout.css
│       ├── layout.erb
│       ├── syntax.css
│       └── user.css
```
The html template directory is used for HTML and PDF output.

Is the epub template directory used to create the .epub and .mobi output?

Can I use a different layout.erb file for the .pdf output? That is, a layout.erb file for html and another layout.erb file for pdf. How do I do that?

**Comment by fnando** [comment]
Long time... but here it goes. v2.0.0 allows you to have different CSS files for each generated file (HTML, PDF, PDF for print, EPUB/MOBI). The layout file is the same for PDF/HTML formats, but a class name is added to the `<html>` element: it can be `html`, `print` or `pdf`. So you can use this to hide/show information on your layout file.
