### ISSUE TITLE
Add support for DocRaptor

### ISSUE THREAD

**Issue by mikeyp** [fnando/kitabu#39]
It'd be nice to be able to use DocRaptor instead of Prince as a configurable option. In theory this should be possible as DocRaptor is literally just an API to Prince.

There's already a gem for DocRaptor as well: https://github.com/expectedbehavior/doc_raptor_gem

**Comment by fnando** [comment]
I added a sample command on the README. It's just a `curl` passing a URL for your e-book. Don't think if it's worth it to add support for this. You can work with PrinceXML locally, and use DocRaptor when you're ready to publish.
