### ISSUE TITLE
Question about chapters in a single source file

### ISSUE THREAD

**Issue by edavis10** [fnando/kitabu#40]
**Question**: Does kitabu require each chapter to be a separate file? Is there any way (or interest) to support separating chapters based on the source text? (e.g. H2s)

**Details**:

I'm using kitabu to process a single markdown file created in a different application (Scrivener). This markdown is my entire book and uses `##` to separate the different chapters. The TOC renders correctly but I noticed that the Prince CSS for `.chapter` wasn't getting applied (specifically the page-break-before). Upon digging into the generated HTML I found there was a `#chapters` element with a single `.chapter` div, with content for the 40 or so real chapters (`##` in the source).

``` html
<div id="chapters">
  <div class"chapter">
    <h2 id="first">First Chapter</h2>
    ....content...
    <h2 id="second">Second Chapter</h2>
    ....content...
  </div>
</div>
```

Picking through the source I was able to change TOC::HTML#normalize to add the `.chapter` class to each of my h2s which gave me the styling I needed but isn't semantically correct (one chapters element with one chapter element).

Picking through the source again, I found Parser::HTML#content (and #chapter_files) is where the chapter class is added but it looks like it's based on the chapter-per-file (or chapter-per-directory-with-many-files).

Ideally I'd want this to happen

(File text/export.md)
``` markdown
## First Chapter

This is the first chapter

## Second Chapter

And here is the second chapter
```

``` html
<div id="chapters">
  <div class"chapter">
    <h2 id="first">First Chapter</h2>
    <p>This is the first chapter</p>
  </div>
  <div class"chapter">
    <h2 id="second">Second Chapter</h2>
    <p>And here is the second chapter</p>
  </div>
</div>
```

**Comment by fnando** [comment]
It was asked a long time ago, but anyway... I think it's possible to do this by tweaking CSS and its chapter counters. Not sure how TOC would be though.
