### ISSUE TITLE
Weird TOC on Epub and Mobi

### ISSUE THREAD

**Issue by simpsonjulian** [fnando/kitabu#48]
My interest is in making a book in Mobi format.  The sample book renders to HTML, Epub and Mobi, but the TOC in the latter two contains lots of text from each page.  , which

I tracked it down to 390eed1b55a33fe9a06a0703cd9c3ca9775ff17b - `lib/kitabu/exporter/epub.rb` - the selector on line 132 seems to match too many elements on the page.  I edited the gem and changed that selector back to the previous one, and it generates a minimal but improved TOC, which looks much better in the Kindle app.

**Comment by yunnysunny** [comment]
I met with the same problem as @simpsonjulian mentioned.I hope the maintainers can fix it as soon as possible.Thanks.

**Comment by fny** [comment]
@simpsonjulian Do you have a fork of your version anywhere?

**Comment by simpsonjulian** [comment]
Hi @fny, I found this diff:

```diff --git a/templates/html/layout.erb b/templates/html/layout.erb
index 84c91c1..0447b22 100644
--- a/templates/html/layout.erb
+++ b/templates/html/layout.erb
@@ -24,9 +24,6 @@

     <div class="table-of-contents">
       <h2 class="no-toc">Contents</h2>
-      <div id="toc">
-        <%= toc %>
-      </div>
     </div>```

     <div id="chapters">

**Comment by TiagoTi** [comment]
hi @fny  if you have a fork, you can try

```ruby
#lib/kitabu/exporter/epub.rb  
def navigation
sections.map do |section|
{
-            label: section.html.css(":first-child").text,
+            label: section.html.css("h2:first-child").text,
  content: section.filename
}
end
```
