### ISSUE TITLE
html2text gives an error on `kitabu export`

### ISSUE THREAD

**Issue by EvanHahn** [fnando/kitabu#49]
When I run `kitabu export`, I get an error with `html2text`.

```
$ kitabu export
Usage: html2text [(filename|url) [encoding]]

html2text: error: no such option: -t
** e-book couldn't be exported
```

When I only build HTML or ePub, everything seems to work:

```
$ kitabu export --only html
** e-book has been exported
$ kitabu export --only epub
** e-book has been exported
```

I installed `html2text` from pip (by running `pip install html2text`). I assume that this is the wrong one?

Here are some potentially relevant details about my system:

```
$ kitabu --version
Kitabu version 2.0.4

$ html2text --version
html2text 2015.6.21

$ kitabu check

Prince XML: Converts HTML files into PDF files.
Not installed.

KindleGen: Converts ePub e-books into .mobi files.
Not installed.

html2text: Converts HTML documents into plain text.
Installed.
```

**Comment by TiagoTi** [comment]
[EvanHahn](https://github.com/EvanHahn), I did like you 

```pip install html2text```

... and got the same result , but when I did the installation by S.O worked perfectly.

```sudo apt-get install html2text```

please confirm if it works

**Comment by EvanHahn** [comment]
@TiagoTi That fixed it! Thank you.
