### ISSUE TITLE
Totally Confused!

### ISSUE THREAD

**Issue by resistorsoftware** [fnando/kitabu#58]
So when I do a **gem install kitabu**, and then _kitabu export_ command, it blows chunks due to some code no longer supported in ActiveSupport. 

Specifically, the normalize function in String. The OLD code is present in tagged version 2.1 which is what we get when we install. That code is old and bugs out. 

So the new code in main is perfect, but we do not get that with gem install. What is the secret sauce to getting the new code when using gem install? 

So version 2.1, lib/kitabu/extensions/string has this old code, which we get with **gem install kitabu**.

        str = ActiveSupport::Multibyte::Chars.new(self.dup)
        str = str.normalize(:kd).gsub(/[^\x00-\x7F]/,'').to_s

But when we see the main branch, we see that code was already all fixed up. 

    str = dup.unicode_normalize(:nfkd)
    str = str.gsub(/[^\x00-\x7F]/, "").to_s

So when I am at my command line, and I want the main branch of kitabu to be my daily driver, what do I use for the install so I do not get the older tagged version?

I downloaded the repository, did a bundle install, and tried a build, but it bombed as it was missing rubocop. So I added rucocop to the gemspec, and then finally _bundle exec rake build_ which gave me the kitabu gem built with the latest code, so I could install it. Seems like a lot of work for something that could just be _gem install kitabu_

**Comment by gregmolnar** [comment]
Maybe you already figured it out, but one way to do that is to clone the repository, run `bundle install` from its root, then you can use `bin/kitabu` to generate a new ebook and in the gemfile of that, you can change the kitabu to point to your local copy: `gem "kitabu", path: "your/local/kitabu/folder"`.

**Comment by fnando** [comment]
This project was kinda abandoned. Kindlegen is not a thing anymore, so export was broken. There were other issues, like the one you mentioned. I didn't complete the whole revamp to make it run with modern ruby, so that's why HEAD code differs from whatever is published to rubygems.

For now, I suggest that you clone this repo, then run `bundle install`. Finally, `rake install` will install the gem on your system.
